### ISSUE TITLE
Read GSE173682_RAW

### ISSUE THREAD

**Issue by linanzhang** [RegnerM2015/scENDO_scOVAR_2020#1]
Hello, I'm interested in your dataset and have downloaded GSE173682_RAW from GEO. I was wondering how to read the three files into Seurat. The commands and error messages read as follows. Thank you.

<img width="470" alt="Screen Shot 2021-11-14 at 11 38 46 PM" src="https://user-images.githubusercontent.com/37935731/141687853-09d15776-75dd-45f6-b8b1-af4a449269dd.png">

I first renamed the files from GSM5276933_matrix-3533EL.mtx.gz to matrix.mtx.gz etc.

**Comment by RegnerM2015** [comment]
Hi @linanzhang,

Thanks for your interest!

Does it work when you download this sample individually? 

GSM5276933 | Patient_1_3533EL_RNA
-- | --

I was not able to reproduce this error when I downloaded this sample individually. Also, could you share the output of `sessionInfo()`?

**Comment by linanzhang** [comment]
`> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3   `

It works when the samples are downloaded individually, but not as a whole. Thank you.
