### ISSUE TITLE
asking for file

### ISSUE THREAD

**Issue by tongyt1225** [RegnerM2015/scENDO_scOVAR_2020#2]
Dear Dr. J. Regner,
Thanks a lot，it is a great work. I have some difficult when running the script. so I want to know if you can upload the ".rds" in your code. Thanks a lot.

**Comment by RegnerM2015** [comment]
Hi @tongyt1225,

Thank you for your interest!

Which script are you trying to run? I may be able to provide the rds file, depending on the script.

**Comment by tongyt1225** [comment]
HI Dr. J. Regner, thank you for taking time to answer my questions.
I very like the analysis of Figure_2.R in Figure_2 folder, it needs the rds files including All_P2G_Observed.rds; All_P2G_Null_example.rds; final_archr_proj_archrGS-P2Gs.rds; Cancer_specific_P2G_table.rds; Cancer_enriched_P2G_table.rds; Fallopian_Tube_Cell_line_Peaks.rds; Ovarian_Epithelial_Cell_line_Peaks.rds; endo_ovar_All_scRNA_processed.rds. 
sorry, it may seem like a lot. 
I really appreciate your help and answering them to the best of your ability.
Best wishes

**Comment by tongyt1225** [comment]
Hi Dr. J. Regner, thank you for taking time to answer my questions.
I very like the analysis of Figure_2.R in Figure_2 folder, it needs the rds files including All_P2G_Observed.rds; All_P2G_Null_example.rds; final_archr_proj_archrGS-P2Gs.rds; Cancer_specific_P2G_table.rds; Cancer_enriched_P2G_table.rds; Fallopian_Tube_Cell_line_Peaks.rds; Ovarian_Epithelial_Cell_line_Peaks.rds; endo_ovar_All_scRNA_processed.rds.
sorry, it may seem like a lot.
I really appreciate your help and answering them to the best of your ability.
Best wishes
Tong yuantao

2022-04-19 19:50:24"Matt Regner" ***@***.***>wrote:

Hi @tongyt1225,

Thank you for your interest!

Which script are you trying to run? I may be able to provide the rds file, depending on the script.

**Comment by RegnerM2015** [comment]
Hi @tongyt1225,

The RDS files are located in this folder on Dropbox: https://www.dropbox.com/sh/dii9hc5ptudyhar/AACZZrAuGhwGRgKbUA0MFEqDa?dl=0

Please let me know if you have trouble downloading them. 

One important note, the final_archr_proj_archrGS-P2Gs.rds is an ArchR Project object. This data object points back to the ArchR Arrow files located on my remote cluster system. Therefore, a lot of the functionality of this object is lost when you load this final_archr_proj_archrGS-P2Gs.rds file into your own environment. 

Also, because your specific R environment (collection of software packages and their versions) is probably different from mine, you still may have trouble running the Figure_2.R script to completion. 

I hope this information helps and best of luck with your research efforts!

**Comment by tongyt1225** [comment]
Hi Dr. J. Regner, thank you for taking time to offer me the rds file.

I am sorry to reply you so late and bother you again. Because I actually have trouble downloading the endo_ovar_All_scRNA_processed.rds(15.5G), which I tried seven times. Each time, I can not get the complete document, the best time obtained the 12.75G file.

For the ArchR Arrow files, I want to know if can get it by running the code at 230-252 row in FullCohort_P2G.R. but it need the final_archr_proj_archrGS.rds, which can be generated by Patients1-11_scATAC-seq.R with the endo_ovar_All_scRNA_processed.rds and wilcox_DEGs.rds. I planned to try the code, but the endo_ovar_All_scRNA_processed.rds can not download.
Thanks a lot.

Best wishes,
Tong yuantao


2022-04-21 07:16:43"Matt Regner" ***@***.***>wrote:

Hi @tongyt1225,

The RDS files are located in this folder on Dropbox: https://www.dropbox.com/sh/dii9hc5ptudyhar/AACZZrAuGhwGRgKbUA0MFEqDa?dl=0

Please let me know if you have trouble downloading them.

One important note, the final_archr_proj_archrGS-P2Gs.rds is an ArchR Project object. This data object points back to the ArchR Arrow files located on my remote cluster system. Therefore, a lot of the functionality of this object is lost when you load this final_archr_proj_archrGS-P2Gs.rds file into your own environment.

Also, because your specific R environment (collection of software packages and their versions) is probably different from mine, you still may have trouble running the Figure_2.R script to completion.

I hope this information helps and best of luck with your research efforts!

**Comment by RegnerM2015** [comment]
Hi @tongyt1225,

I am sorry that you are having trouble downloading the endo_ovar_All_scRNA_processed.rds. It is quite large after all, and depending on your download speeds and computational environment you may run into issues downloading it. I am not sure how to troubleshoot this. 

The other option is to generate this endo_ovar_All_scRNA_processed.rds file yourself using the data deposited in the Gene Expression Omnibus (GEO) accession GSE173682. 

Once you download the GEO data, you can try running the scripts located in this folder: https://github.com/RegnerM2015/scENDO_scOVAR_2020/tree/main/scRNA-seq%20Processing%20Scripts

**Comment by tongyt1225** [comment]
Hi,  Dr. J. Regner, 
Thanks you a lot for your reply. 
I  tried the method your advice but it need the some other files when running. if you can upload the zip file of endo_ovar_All_scRNA_processed.rds.
 I will try some other methods. I am sorry to take up your valuable time.
Thanks a lot
Tong yuantao

2022-04-22 10:15:02"Matt Regner" ***@***.***>wrote:

Hi @tongyt1225,

I am sorry that you are having trouble downloading the endo_ovar_All_scRNA_processed.rds. It is quite large after all, and depending on your download speeds and computational environment you may run into issues downloading it. I am not sure how to troubleshoot this.

The other option is to generate this endo_ovar_All_scRNA_processed.rds file yourself using the data deposited in the Gene Expression Omnibus (GEO) accession GSE173682.

Once you download the GEO data, you can try running the scripts located in this folder: https://github.com/RegnerM2015/scENDO_scOVAR_2020/tree/main/scRNA-seq%20Processing%20Scripts

**Comment by RegnerM2015** [comment]
Hi @tongyt1225,

I uploaded a zip file and a version with tar.gz compression. The following files should now be in the Dropbox folder:

endo_ovar_All_scRNA_processed.rds.zip
endo_ovar_All_scRNA_processed.tar.gz

Let me know if you have trouble downloading and/or extracting these!

**Comment by tongyt1225** [comment]
thanks a lot, I get it successfully.

**Comment by RegnerM2015** [comment]
Happy to help! I will close the issue for now, but feel free to reopen the issue if you have follow up questions.

**Comment by CYGRY** [comment]
Hello, Dr. J. Regner,
I found that the RDS file in [https://www.dropbox.com/sh/dii9hc5ptudyhar/AABCMu9wrjDk8BUAW7Iyca-9a/Regner_Wisniewska_etal_Annotated_Seurat_Objects?dl=0&subfolder_nav_tracking=1](url)  seems to be missing patient 9's data. Could you please upload it?
Best wishes
Chunyu
