### ISSUE TITLE
patient 9's data

### ISSUE THREAD

**Issue by CYGRY** [RegnerM2015/scENDO_scOVAR_2020#4]
Hello, Dr. J. Regner,
I found that the RDS file in [https://www.dropbox.com/sh/dii9hc5ptudyhar/AABCMu9wrjDk8BUAW7Iyca-9a/Regner_Wisniewska_etal_Annotated_Seurat_Objects?dl=0&subfolder_nav_tracking=1](https://github.com/RegnerM2015/scENDO_scOVAR_2020/issues/url) seems to be missing patient 9's data. Could you please upload it?
Best wishes
Chunyu

**Comment by RegnerM2015** [comment]
Hi Chunyu,

I can work on uploading the processed Seurat object for this sample, but I would recommend downloading data from GEO:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE173682 

Specifically, the Seurat object for patient 9 can be found here: 

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5276943

**Comment by CYGRY** [comment]
Hello, Dr. J. Regner,
I attempted to create a new rds file based on the data obtained from GEO, but due to a problem with the R version, the cbind function was unusable. When I created a new cbind function, it made R unable to recognize DATA$SYMBOL, resulting in an error.
<img width="781" alt="截屏2023-10-09 01 05 58" src="https://github.com/RegnerM2015/scENDO_scOVAR_2020/assets/97320872/16822ec9-2c0c-4883-aa47-7a2c6b63fa38">
Sorry to bother you! Thank you again!
Best wishes
Chunyu

**Comment by CYGRY** [comment]
Thank you very much for your reply and help. I am using an M1 chip Macbook, so there may be significant environmental differences. I am trying to replicate HGSOC's data analysis, and currently I have obtained ovar based on previous issues from others_ 3BAE2L_ ScRNA_ Processed.rds file, could you please upload the rds file corresponding to 3E5CFL. Thanks a lot!
Best wishes
Chunyu

**Comment by CYGRY** [comment]
Thank you very much for your help. I have resolved the compatibility issue by replacing another computer device.
